CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ID_Alumno] INT NOT NULL, 
    [cod_Curso] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_ALUMNO] FOREIGN KEY ([ID_Alumno]) REFERENCES [ALUMNO](Id), 
    CONSTRAINT [FK_INSCRITO_CURSO] FOREIGN KEY ([cod_Curso]) REFERENCES [CURSO]([cod])
)
